import { Project, Service, PhotoItem } from './types';

export const CATEGORY_LABELS: Record<string, string> = {
  all: 'All Works',
  wedding: 'Wedding Film',
  commercial: 'Commercial',
  corporate: 'Corporate',
  event: 'Event',
  content: 'Content',
};

export const PHOTO_CATEGORIES: Record<string, string> = {
  all: 'ALL',
  beards: 'BEARDS',
  hairstyle: 'HAIRSTYLE',
  haircut: 'HAIRCUT',
  mustaches: 'MUSTACHES',
  portrait: 'PORTRAIT',
  new: 'NEW',
};

export const INITIAL_PHOTOS: PhotoItem[] = [
  {
    id: 'photo_1',
    title: 'Master Barber Precision Haircut',
    category: 'haircut',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
    description: 'Proses potong rambut presisi tinggi dengan teknik fade modern.',
    aspectRatio: 'tall',
  },
  {
    id: 'photo_2',
    title: 'Traditional Lather & Hot Towel Shave',
    category: 'beards',
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=80',
    description: 'Layanan cukur jenggot klasik dengan busa hangat dan pisau lipat tradisional.',
    aspectRatio: 'wide',
  },
  {
    id: 'photo_3',
    title: 'Precision Clipper Fade & Styling',
    category: 'hairstyle',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=1200&q=80',
    description: 'Teknik penataan rambut pria kontemporer menggunakan pomade berkualitas tinggi.',
    aspectRatio: 'wide',
  },
  {
    id: 'photo_4',
    title: 'Vintage Barber Shop Interior & Chair',
    category: 'new',
    imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
    description: 'Suasana interior barbershop bergaya vintage dengan kursi kulit klasik.',
    aspectRatio: 'square',
  },
  {
    id: 'photo_5',
    title: 'Mid Fade & Edge Up Detail',
    category: 'haircut',
    imageUrl: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=800&q=80',
    description: 'Detail garis tepi rambut bersih dan potongan fade bertingkat.',
    aspectRatio: 'square',
  },
  {
    id: 'photo_6',
    title: 'Classic Grooming & Styling Session',
    category: 'hairstyle',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    description: 'Sesi penataan rambut dan perawatan wajah lengkap untuk pria elegan.',
    aspectRatio: 'square',
  },
  {
    id: 'photo_7',
    title: 'Contemporary Urban Portrait',
    category: 'portrait',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=80',
    description: 'Fotografi potret pria dengan pencahayaan sinematik yang kuat.',
    aspectRatio: 'wide',
  },
  {
    id: 'photo_8',
    title: 'Full Beard & Handlebar Mustache Sculpting',
    category: 'mustaches',
    imageUrl: 'https://images.unsplash.com/photo-1618077360395-f3068be8e001?auto=format&fit=crop&w=800&q=80',
    description: 'Perawatan dan pembentukan kumis serta jenggot pria dengan gunting presisi.',
    aspectRatio: 'tall',
  },
  {
    id: 'photo_9',
    title: 'Studio Lighting Portraiture',
    category: 'portrait',
    imageUrl: 'https://i.postimg.cc/Cxk2bDzh/Chat-GPT-Image-Jul-27-2026-04-43-18-PM.png',
    description: 'Dokumentasi fotografi medis & profil profesional dr. Intan Wulandari.',
    aspectRatio: 'tall',
  },
  {
    id: 'photo_10',
    title: 'Cinematic Bromo Mountain Landscape',
    category: 'new',
    imageUrl: 'https://i.postimg.cc/G2JkNNWC/Chat-GPT-Image-Jul-22-2026-05-17-00-PM.png',
    description: 'Keindahan lautan pasir dan keajaiban lanskap Gunung Bromo.',
    aspectRatio: 'wide',
  },
];


export const INITIAL_PROJECTS: Project[] = [
  // PORTRAIT PROJECTS (7 Items)
  {
    id: 'p_reel_1',
    filterKey: 'content',
    category: 'Content Creation',
    name: 'Lahir Daging Panggang yang Istimewa',
    desc: 'Konten kuliner yang menampilkan proses dan hasil daging panggang istimewa, dikemas secara sinematik dan menggugah selera.',
    tags: ['Culinary', 'Cinematic', '4K'],
    bg: 'linear-gradient(135deg,#1a0d0d 0%,#220d0d 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/28hQWsKQ/Makanan-segar-dengan-bahan-bahan-bumbu.png',
    video: 'https://youtube.com/shorts/hbmXe3wSuwc?si=JNNy50yS_-MBUPhM',
    isPortrait: true,
  },
  {
    id: 'p_reel_2',
    filterKey: 'content',
    category: 'Content Creation',
    name: 'Long Time No See',
    desc: 'Sebuah karya sinematik yang mengangkat tema pertemuan dan kerinduan, dihadirkan dengan visual yang emosional dan penuh cerita.',
    tags: ['Cinematic', 'Storytelling', '4K'],
    bg: 'linear-gradient(135deg,#1a0d1a 0%,#220d22 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/Kv6Tv0c3/Whats-App-Image-2026-07-22-at-16-29-45.jpg',
    video: 'https://youtube.com/shorts/BS6MUz-Wzmc?si=cp2hSjRWpR6mvO7G',
    isPortrait: true,
  },
  {
    id: 'p_reel_3',
    filterKey: 'commercial',
    category: 'Commercial Video',
    name: 'Ligat Internet',
    desc: 'Video promosi Ligat Internet dengan pendekatan visual yang menarik, menonjolkan keunggulan layanan secara jelas dan meyakinkan.',
    tags: ['Commercial', 'Promo', '4K'],
    bg: 'linear-gradient(135deg,#0d141a 0%,#0d1c26 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/dt2WFZv4/Whats-App-Image-2026-07-22-at-16-43-34.jpg',
    video: 'https://youtube.com/shorts/leh0iiOF7hM?si=Mhp73vdL4Qn-Onlf',
    isPortrait: true,
  },
  {
    id: 'p_reel_4',
    filterKey: 'event',
    category: 'Event Documentation',
    name: 'Perpisahan Camp Kampung Inggris',
    desc: 'Dokumentasi momen perpisahan camp Kampung Inggris, mengabadikan kebersamaan dan kenangan berharga selama program berlangsung.',
    tags: ['Event', 'Documentation', '4K'],
    bg: 'linear-gradient(135deg,#0d1a14 0%,#0d221a 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/sX5WWSnz/Whats-App-Image-2026-07-22-at-16-45-52.jpg',
    video: 'https://youtu.be/a2vJdhQFDqE?si=FOL7AOHbO_Qu5pgY',
    isPortrait: true,
  },
  {
    id: 'p_reel_5',
    filterKey: 'event',
    category: 'Event Documentation',
    name: 'Soft Opening 4Care Medical Centre',
    desc: 'Dokumentasi momen soft opening 4Care Medical Centre, mengabadikan seremoni dan momen penting acara secara sinematik.',
    tags: ['Event', 'Opening', '4K'],
    bg: 'linear-gradient(135deg,#0d1a1c 0%,#0d2226 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/9M0SFm19/Whats-App-Image-2026-07-22-at-16-50-15.jpg',
    video: 'https://youtube.com/shorts/COs65BufvWM?si=2dMkXOi5hYiVSKVl',
    isPortrait: true,
  },
  {
    id: 'p_reel_6',
    filterKey: 'content',
    category: 'Content Creation',
    name: 'Profil Dokter Intan Wulandari - 4Care',
    desc: 'Video perkenalan dan edukasi dr. Intan Wulandari, DH (Dokter Hematologi) di 4Care Medical Center.',
    tags: ['Medical', 'Doctor', '4Care', 'Reels'],
    bg: 'linear-gradient(135deg, #0d1a1c 0%, #0d2226 40%, #0d0d0d 100%)',
    image: 'https://i.postimg.cc/Cxk2bDzh/Chat-GPT-Image-Jul-27-2026-04-43-18-PM.png',
    video: 'https://youtube.com/shorts/6V8dU8sCESc?feature=shared',
    isPortrait: true,
  },
  {
    id: 'p_reel_7',
    filterKey: 'content',
    category: 'Portrait Reels',
    name: 'Streetwear Style Reels',
    desc: 'Video katalog modern bergaya streetwear perkotaan dengan transisi cepat dan music beat-sync.',
    tags: ['Fashion', 'Streetwear', 'TikTok', 'Dynamic'],
    bg: 'linear-gradient(135deg, #0f1c24 0%, #050a0f 100%)',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&h=1066&q=80',
    video: 'https://www.youtube.com/embed/obxyTHGFfHQ',
    isPortrait: true,
  },

  // LANDSCAPE PROJECTS (6 Items)
  {
    id: 'p_land_1',
    filterKey: 'content',
    category: 'Content Creation',
    name: 'Jejak di Antara Waktu',
    desc: 'Sebuah karya sinematik yang menelusuri jejak waktu, menghadirkan narasi visual yang mendalam dan penuh emosi.',
    tags: ['Cinematic', 'Film', '4K', 'Storytelling'],
    bg: 'linear-gradient(135deg,#12141a 0%,#1c1a2d 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/Y9ZfHMhN/Chat-GPT-Image-Jul-22-2026-03-53-40-PM.png',
    video: 'https://youtu.be/vyvOGtodOEo?si=kM3fc7h9JFp7PseM',
    isPortrait: false,
  },
  {
    id: 'p_land_2',
    filterKey: 'content',
    category: 'Content Creation',
    name: 'Weekend in Bromo — Cinematic Film',
    desc: 'Perjalanan akhir pekan sinematik ke Gunung Bromo, mengabadikan keindahan alam dan momen tak terlupakan dalam visual yang memukau.',
    tags: ['Cinematic', 'Travel', '4K', 'Bromo'],
    bg: 'linear-gradient(135deg,#1a1008 0%,#2d1a08 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/8P89dVZ8/Chat-GPT-Image-Jul-22-2026-04-09-58-PM.png',
    video: 'https://youtu.be/zy8RB12gUYo?si=nGOkHzz0n_eFdhLA',
    isPortrait: false,
  },
  {
    id: 'p_land_3',
    filterKey: 'content',
    category: 'Content Creation',
    name: 'Diversity — Cinematic Film Batam',
    desc: 'Film sinematik yang merayakan keberagaman di Batam, menghadirkan visual storytelling yang kuat dan penuh makna.',
    tags: ['Cinematic', 'Film', '4K', 'Batam'],
    bg: 'linear-gradient(135deg,#0d1a1a 0%,#0d2020 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/GhJ7kTB2/Chat-GPT-Image-Jul-22-2026-04-10-04-PM.png',
    video: 'https://youtu.be/fIMf6IZ_5So?si=ITjJ6Auyg_UR9mUr',
    isPortrait: false,
  },
  {
    id: 'p_land_4',
    filterKey: 'content',
    category: 'Content Creation',
    name: 'cinematic by viu_mikke',
    desc: 'Konten cinematic travel yang mengabadikan keindahan Gunung Bromo, menampilkan keajaiban alam Indonesia melalui visual yang memukau.',
    tags: ['Cinematic', 'Travel', '4K', 'Indonesia'],
    bg: 'linear-gradient(135deg,#1a1408 0%,#2d2008 40%,#0d0d0d 100%)',
    image: 'https://i.postimg.cc/G2JkNNWC/Chat-GPT-Image-Jul-22-2026-05-17-00-PM.png',
    video: 'https://youtu.be/gczVSl7CVIc?si=L1i9Kr_67LKHVyAs',
    isPortrait: false,
  },
  {
    id: 'p_land_5',
    filterKey: 'wedding',
    category: 'Wedding Film',
    name: 'Elegance in Batam — Wedding Highlight',
    desc: 'Dokumentasi pernikahan eksklusif berlatar pemandangan pesisir Batam, mengemas momen suci dengan estetika emosional.',
    tags: ['Wedding', 'Cinematic', '4K Ultra HD', 'Highlight'],
    bg: 'linear-gradient(135deg, #2d1a08 0%, #1a0f04 100%)',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    video: 'https://www.youtube.com/embed/obxyTHGFfHQ',
    isPortrait: false,
  },
  {
    id: 'p_land_6',
    filterKey: 'commercial',
    category: 'Commercial Video',
    name: 'Aroma Kopi — Cafe Commercial',
    desc: 'Video sinematik promosi kedai kopi lokal, mengemas pembuatan kopi presisi tinggi dengan nuansa hangat.',
    tags: ['Commercial', 'Promo', 'Coffee', 'Warm'],
    bg: 'linear-gradient(135deg, #2c1a11 0%, #150c07 100%)',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80',
    video: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    isPortrait: false,
  },
];

export const SERVICES: Service[] = [
  {
    num: '01',
    title: 'Content Creation',
    desc: 'Produksi konten video kreatif untuk media sosial, digital campaign, dan branding. Menghadirkan visual estetik yang meningkatkan interaksi audiens.',
    tags: ['Reels', 'TikTok', 'Short Form', 'Social Media'],
  },
  {
    num: '02',
    title: 'Commercial Video',
    desc: 'Iklan komersial produk dan jasa dengan sinematografi kelas atas dan alur cerita yang persuasif untuk memperkuat pemasaran produk Anda.',
    tags: ['TVC', 'Brand Film', 'Product Ads', 'Campaign'],
  },
  {
    num: '03',
    title: 'Company Profile',
    desc: 'Pengembangan media visual profil perusahaan yang profesional, informatif, dan menginspirasi untuk meningkatkan reputasi korporasi di mata klien.',
    tags: ['Corporate', 'Business Profile', 'Documentary'],
  },
  {
    num: '04',
    title: 'Event Documentation',
    desc: 'Abadikan keseruan dan momen-momen penting dari acara perusahaan, peluncuran produk, hingga konferensi internasional dengan kualitas premium.',
    tags: ['Seminar', 'Launch Event', 'Exhibition Recap'],
  },
  {
    num: '05',
    title: 'Wedding Film',
    desc: 'Abadikan kisah cinta abadi Anda dalam dokumentasi pernikahan bergaya sinematik yang kaya akan rasa, kejujuran momen, dan keindahan estetis.',
    tags: ['Cinematic', 'SDE', 'Documentary Wedding'],
  },
];
